# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/h/baoyan/SIGMOD/src/baseline

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/h/baoyan/SIGMOD/src/baseline

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/h/baoyan/SIGMOD/src/baseline/CMakeFiles /mnt/h/baoyan/SIGMOD/src/baseline//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/h/baoyan/SIGMOD/src/baseline/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named knng

# Build rule for target.
knng: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 knng
.PHONY : knng

# fast build rule for target.
knng/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/knng.dir/build.make CMakeFiles/knng.dir/build
.PHONY : knng/fast

HyRec.o: HyRec.cpp.o
.PHONY : HyRec.o

# target to build an object file
HyRec.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/knng.dir/build.make CMakeFiles/knng.dir/HyRec.cpp.o
.PHONY : HyRec.cpp.o

HyRec.i: HyRec.cpp.i
.PHONY : HyRec.i

# target to preprocess a source file
HyRec.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/knng.dir/build.make CMakeFiles/knng.dir/HyRec.cpp.i
.PHONY : HyRec.cpp.i

HyRec.s: HyRec.cpp.s
.PHONY : HyRec.s

# target to generate assembly for a file
HyRec.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/knng.dir/build.make CMakeFiles/knng.dir/HyRec.cpp.s
.PHONY : HyRec.cpp.s

kdtree.o: kdtree.cc.o
.PHONY : kdtree.o

# target to build an object file
kdtree.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/knng.dir/build.make CMakeFiles/knng.dir/kdtree.cc.o
.PHONY : kdtree.cc.o

kdtree.i: kdtree.cc.i
.PHONY : kdtree.i

# target to preprocess a source file
kdtree.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/knng.dir/build.make CMakeFiles/knng.dir/kdtree.cc.i
.PHONY : kdtree.cc.i

kdtree.s: kdtree.cc.s
.PHONY : kdtree.s

# target to generate assembly for a file
kdtree.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/knng.dir/build.make CMakeFiles/knng.dir/kdtree.cc.s
.PHONY : kdtree.cc.s

knn-construction.o: knn-construction.cc.o
.PHONY : knn-construction.o

# target to build an object file
knn-construction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/knng.dir/build.make CMakeFiles/knng.dir/knn-construction.cc.o
.PHONY : knn-construction.cc.o

knn-construction.i: knn-construction.cc.i
.PHONY : knn-construction.i

# target to preprocess a source file
knn-construction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/knng.dir/build.make CMakeFiles/knng.dir/knn-construction.cc.i
.PHONY : knn-construction.cc.i

knn-construction.s: knn-construction.cc.s
.PHONY : knn-construction.s

# target to generate assembly for a file
knn-construction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/knng.dir/build.make CMakeFiles/knng.dir/knn-construction.cc.s
.PHONY : knn-construction.cc.s

utils.o: utils.cpp.o
.PHONY : utils.o

# target to build an object file
utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/knng.dir/build.make CMakeFiles/knng.dir/utils.cpp.o
.PHONY : utils.cpp.o

utils.i: utils.cpp.i
.PHONY : utils.i

# target to preprocess a source file
utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/knng.dir/build.make CMakeFiles/knng.dir/utils.cpp.i
.PHONY : utils.cpp.i

utils.s: utils.cpp.s
.PHONY : utils.s

# target to generate assembly for a file
utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/knng.dir/build.make CMakeFiles/knng.dir/utils.cpp.s
.PHONY : utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... knng"
	@echo "... HyRec.o"
	@echo "... HyRec.i"
	@echo "... HyRec.s"
	@echo "... kdtree.o"
	@echo "... kdtree.i"
	@echo "... kdtree.s"
	@echo "... knn-construction.o"
	@echo "... knn-construction.i"
	@echo "... knn-construction.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

